### ISSUE TITLE
Can you make this run as a daemon?

### ISSUE THREAD

**Issue by IOcase** [DemmyDemon/ark_rcon#1]
I don't know much about daemon processes on linux. I'd like to have this running in the background all the time without having to have a console open while also having the option to go interactive with the process again if I want to. Would that be too much work?

**Comment by DemmyDemon** [comment]
You want [screen](https://linux.die.net/man/1/screen) or [tmux](https://linux.die.net/man/1/tmux).
I prefer tmux myself, but screen can be easier to wrap your head around if you're new to Linux.
